### PR TITLE
PDF Generator update

### PR DESCRIPTION
**Pull request by DanielC-N**
added a button on the top right corner to generate a PDF from one or more project with different downloaded resources.

### CODE REVIEW

**Comment by DanielC-N** [comment]
actions/upload-artifact@v1 is now deprecated and unusable.
Today I received an error from github actions : `"Error: This request has been automatically failed because it uses a deprecated version of **actions/upload-artifact: v1**. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/"`

**Comment by selvabenz** [comment]
@DanielC-N, the PR looks good. there are some suggestions I have.

1. If you could keep the Scribe UI standard, the whole UI would look consistent. @arpitjacob can help you with the UI standards
2. **Reset parameters** is inactive when I want to reset
3. Start page side, user may understand Right and Left easily than Recto and Verso. (just a suggestion) 
4. In "**Your file name here**", unable to give any **space and special character**. if it is kept intentionally, ignore this
5. **Add validation message** for the "Choose export Folder" and "Your file name here" if "Choose export Folder" not chosen  or "Your file name here" name typed 
6. **Add validation message** for OBS start and end
7. If "Your file name here" is empty it is taking random alphabet and generates the PDF
8. On one instance I did not select "show page number but in the message area it shows "Generate Page Numbers"
9. **Add complete or failed message** when the printing is done or failed 
10. Sample PDF of the Juxta, OBS and Text translation 
[Test.pdf](https://github.com/user-attachments/files/16958630/Test.pdf)
[b.pdf](https://github.com/user-attachments/files/16958594/b.pdf)
[t.pdf](https://github.com/user-attachments/files/16958595/t.pdf)


All the other functions are looking good.

**Comment by DanielC-N** [comment]
1. If you could keep the Scribe UI standard, the whole UI would look consistent. @arpitjacob can help you with the UI standards :x:
2. **Reset parameters** is inactive when I want to reset ✅
3. Start page side, user may understand Right and Left easily than Recto and Verso. (just a suggestion) :x: 
4. In "**Your file name here**", unable to give any **space and special character**. if it is kept intentionally, ignore this => This is intentional but I added a notice  ✅
5. **Add validation message** for the "Choose export Folder" and "Your file name here" if "Choose export Folder" not chosen  or "Your file name here" name typed  ✅
6. **Add validation message** for OBS start and end ❓
7. If "Your file name here" is empty it is taking random alphabet and generates the PDF => I put a string of random words ✅
8. On one instance I did not select "show page number but in the message area it shows "Generate Page Numbers"  ✅
9. **Add complete or failed message** when the printing is done or failed  ✅

**Comment by selvabenz** [comment]
Thanks, @DanielC-N for updating the PR.

I have made a video to explain point no 6 **Add validation message for OBS start and end ❓**
https://www.awesomescreenshot.com/video/31440031?key=012d2af149814967156640a5b86a9140

**Comment by DanielC-N** [comment]
@selvabenz I've hidden the print button on audio projects.
After the discussion for the OBS. Nothing was changed.

**Comment by selvabenz** [comment]
@vipinpaul, all the necessary corrections are made by @DanielC-N, we can go for a merge.

**Pull request merged**
