### PR TITLE
Ft/project management

### PR DESCRIPTION
**Pull request by vipinpaul**
Book and Chapter level scope selection for audio projects

### CODE REVIEW

**Comment by selvabenz** [comment]
While editing the project in the Audio flavor, the following error pops-up
image

**Comment by selvabenz** [comment]
on the first selection, the selected chapters are not active in the navigation window. The selected chapter is active only on the second opening. 

image

image

image

**Comment by selvabenz** [comment]
Without selecting the chapter in the project management we can record the verse of the first chapter
image

**Comment by selvabenz** [comment]
> Without selecting the chapter in the project management we can record the verse of the first chapter image

This issue has been fixed: Now without selecting the chapter in the Manage Project the chapter can't be recorded 

image

**Comment by selvabenz** [comment]
@vipinpaul, While testing, with the edit menu except for one project all the other projects worked well. Since it occurs only on one project this PR can be merged.

**Review by joelthe1 — APPROVED** [review]

**Pull request merged**
