### PR TITLE
Modification of Logic

### LINKED ISSUE #315: The default Bible resources page should show aligned Bibles
Currently the English resources that are shown by default are ones that aren't recommended.
ScribeResources

Instead of showing English unaligned Bibles, the default resources should be unaligned. It should look like this: 
CleanShot 2024-04-05 at 12 33 32@2x

### LINKED ISSUE #316: 'Save Filter' button should just say 'Filter'
CleanShot 2024-04-05 at 12 33 32@2x

It is confusing to users for the resource search button to say "save filter'. The green button should say 'Filter'. 

Definition of Done
---
The green button on the resources page has text that makes it clear what it will do.

### PR DESCRIPTION
**Pull request by sijumoncy**
- FIXED #316 
- FIXED #315 
- Feature Change

### CODE REVIEW

**Comment by selvabenz** [comment]
All the changes are reflected and the functions that are related to these changes are working as expected. This PR can be merged.

image

**Comment by selvabenz** [comment]
@sijumoncy and @vipinpaul there is a correction in the requirement. Birch says, "I think it should default to aligned. And then have options for aligned, unaligned, and both". Please make the changes as mentioned.

**Comment by selvabenz** [comment]
@sijumoncy  please remove the type
 auto selection.

image

**Comment by selvabenz** [comment]
@vipinpaul all the necessary changes have been made and reflected as expected. Therefore please merge this PR.

image

**Review by vipinpaul — APPROVED** [review]

**Pull request merged**
